### ISSUE TITLE
if the city doesn't exist or misspelled then it crashes

### ISSUE THREAD

**Issue by hugoledoux** [HideBa/ahn_cli#6]
```
ahn_cli -o ./out.laz -c "Delft123"
Traceback (most recent call last):
  File "/Users/hugo/.pyenv/versions/ahncli/bin/ahn_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/ahn_cli/main.py", line 121, in main
    if validate_all(
       ^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/ahn_cli/validator.py", line 104, in validate_all
    validate_city(city_name, cfg.city_polygon_file)
  File "/Users/hugo/.pyenv/versions/3.11.2/envs/ahncli/lib/python3.11/site-packages/ahn_cli/validator.py", line 22, in validate_city
    raise ValueError("City name not found in city list.")
ValueError: City name not found in city list.
```

**Comment by HideBa** [comment]
fix will be released w v0.2.0
